#version 450

#extension GL_KHR_shader_subgroup_ballot: enable

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

const uint poolSize = 1930176;
const float PI = 3.1415926f;

layout (binding = 1) restrict buffer pathStatePool { 
    vec4 origin[poolSize]; // only one array can be of variable length, hardcode the length unfort
    vec4 direction[poolSize];
    vec4 hitNormal[poolSize];
    vec4 throughput[poolSize];
} pathPool;

layout (binding = 2) restrict buffer extensionRayQueue {
    uint size; // atomic number representing the size of the queue
    uint requests[poolSize]; // each entry is the path index needed to be extended
} extensionQueue;

layout (binding = 3) restrict buffer materialRequestQueue {
    uint size; // atomic number representing the size of the queue
    uint requests[poolSize]; // each entry is the path index needed to be extended
} materialQueue;

float random(inout uint state) {
    state = state * 747796405 + 2891336453;
    uint result = ((state >> ((state >> 28) + 4)) ^ state) * 277803737;
    result = (result >> 22) ^ result;
    return result / 4294967295.f;
}

vec3 cosineHemisphereDir(vec3 rayNormal, inout uint state) {
    float r1 = random(state);
    float r2 = random(state);

    // found by integrating the pdf 2pi cos(theta)/pi sin(theta) dtheta
    float phi = 2 * PI * r1;
    float sqrtR2 = sqrt(r2);
    float x = cos(phi) * sqrtR2;
    float y = sin(phi) * sqrtR2;
    float z = sqrt(1 - r2);

    // generate orthonormal basis based on normal
    vec3 zAlignedDir = vec3(x, y, z);
    vec3 nonParallelAxis = abs(dot(rayNormal, vec3(1.f, 0.f, 0.f))) < 1.f ? vec3(1.f, 0.f, 0.f) : vec3(0.f, 0.f, 1.f);
    vec3 t = normalize(cross(rayNormal, nonParallelAxis));
    vec3 b = cross(rayNormal, t);
    mat3 changeOfBasis = {t, b, rayNormal};

    return changeOfBasis * zAlignedDir;
}

void main() {
    //ivec2 dim = imageSize(outImage);  // hard coded for now, maybe push the dimensions to give the size
    ivec2 dim = {1728, 1117};
    ivec2 uv = ivec2(gl_GlobalInvocationID.x % dim.x, gl_GlobalInvocationID.x / dim.x);

    uint threadIndex = gl_GlobalInvocationID.x;
    if (materialQueue.size > 0) return;
    // if (threadIndex >= materialQueue.size) return; // if too many threads dispatched
    // if (extensionQueue.size >= poolSize) return;

    uint state = threadIndex;
    uint poolIndex = materialQueue.requests[threadIndex];
    vec4 normal = pathPool.hitNormal[poolIndex];
    vec3 newDir = cosineHemisphereDir(normal.xyz, state);
    pathPool.origin[poolIndex] = vec4(pathPool.direction[poolIndex].xyz + normal.xyz * normal.w, 0.f);
    pathPool.direction[poolIndex] = vec4(newDir, 0.f);

    // write requests to the extension queue
    bool predicate = true;
    uvec4 ballot = subgroupBallot(predicate);
    uint oldSize = 0;
    if (subgroupElect()) {
        uint activeThreads = subgroupBallotBitCount(ballot);
        oldSize = atomicAdd(extensionQueue.size, activeThreads); // returns the number before the atomic add

        // when all paths get put into extension queue, we finish
        if (oldSize + activeThreads == materialQueue.size) {
            materialQueue.size = 0;
        }
    }
    // bit shift the ballot and count the number of 1 bits removed, this is the index for the request
    uvec4 shifted = ballot << gl_SubgroupInvocationID;
    uint threadBitCount = 128 - subgroupBallotBitCount(shifted);

    // synchronize value for all subgroup threads
    uint offset = subgroupBroadcast(oldSize, 0);
    if (predicate) {
        materialQueue.requests[offset + threadBitCount] = poolIndex;
    }
}