#version 450

#extension GL_KHR_shader_subgroup_ballot: enable

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

const uint poolSize = 1930176;
const float PI = 3.1415926f;

struct CameraInfo {
    mat4 cameraRotation;
    vec3 pos;
    float nearPlane;
    float aspectRatio;
    float fov;
};

layout (binding = 0, rgba8) uniform image2D outImage;

layout (binding = 1) buffer pathStatePool { 
    vec4 origin[poolSize]; // only one array can be of variable length? do i hardcode the length (probably)
    vec4 direction[poolSize];
} pathPool;

layout (binding = 2) restrict buffer newPathQueue {
    uint size; // atomic number representing the size of the queue
    uint requests[poolSize]; // each entry is the path index needed to be generated 
} pathQueue;

layout (binding = 3) restrict buffer extensionRayQueue {
    uint size; // atomic number representing the size of the queue
    uint requests[poolSize]; // each entry is the path index needed to be extended
} extensionQueue;

// layout (push_constant) uniform constants {
//     CameraInfo camInfo;
// } PushConstants;

void main() {
    ivec2 dim = imageSize(outImage);  // hard coded for now, maybe push the dimensions to give the size
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / dim;

    uint threadIndex = gl_GlobalInvocationID.y * dim.x + gl_GlobalInvocationID.x;
    if (threadIndex >= pathQueue.size) return; // if too many threads dispatched

    // generate ray; from sebastian lague, probably from unity docs
    CameraInfo cam = {
        mat4(1.f),
        vec3(0.f),
        0.1f,
        float(dim.x) / dim.y,
        50.f
    };

    float planeHeight = cam.nearPlane * tan(radians(cam.fov * 0.5f)) * 2.f;
    float planeWidth = planeHeight * cam.aspectRatio;

    vec3 bottomLeft = vec3(-planeWidth / 2.f, -planeHeight / 2.f, 0.1f);
    vec3 point = bottomLeft + vec3(planeWidth * uv.x, planeHeight * uv.y, 0.f);
    
    // update path state
    uint poolIndex = pathQueue.requests[threadIndex];
    pathPool.origin[poolIndex] = vec4(cam.pos, 0.f);
    pathPool.direction[poolIndex] = (vec4(normalize(point), 1.f));

    // sync the threads and clear the queue
    memoryBarrierBuffer();
    pathQueue.size = 0;

    // write requests to the raycast queue (probably wrong lol)
    // which one first for proper sync?? need to test..
    extensionQueue.requests[extensionQueue.size + gl_SubgroupInvocationID] = poolIndex;
    uvec4 ballot = subgroupBallot(true);
    if (subgroupElect()) {
        atomicAdd(extensionQueue.size, subgroupBallotBitCount(ballot)); // num of active threads
    }
}