#version 450

#extension GL_KHR_shader_subgroup_ballot: enable

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

const uint poolSize = 1930176;

layout (binding = 0, rgba8) uniform image2D outImage;

layout (binding = 1) buffer pathStatePool { 
    vec4 origin[poolSize]; // only one array can be of variable length? do i hardcode the length (probably)
    vec4 direction[poolSize];
} pathPool;

layout (binding = 3) buffer extensionRayQueue {
    uint size; // atomic number representing the size of the queue
    uint requests[poolSize]; // each entry is the path index needed to be extended
} extensionQueue;

void main() {
    ivec2 dim = imageSize(outImage);
    uint threadIndex = (gl_GlobalInvocationID.y * dim.x + gl_GlobalInvocationID.x);
    if (threadIndex >= poolSize) return;

    uint index = extensionQueue.requests[threadIndex];
    vec3 finalColor = vec3(pathPool.direction[threadIndex].rgb) * pathPool.direction[threadIndex].a;
    if (any(isnan(finalColor))) finalColor = vec3(1.f, 0.f, 1.f);

    imageStore(outImage, ivec2(gl_GlobalInvocationID.xy), vec4(finalColor, 1.f));
}